print(5)
print(5+10)
print(3.14)
print(500_000)
print("'Hello Python'")
print('"Hello Python"')
print("Hello \"Python\"")
print(type(200_000))
print(type(3.14))
print(type(True))
print(type("True"))
print(True)
print(False)
age = 35 + 1
print(age)
age = age-36
print(age)
print(type(age))
print(("ab" * 40) + ("CD" * 20))